
spring:
  datasource:
    url: jdbc:mysql://studay.ccffdvvcdhfd.ap-northeast-1.rds.amazonaws.com:3306/studay?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: studay
    password: gmrrn123
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info