package org.guzzing.studay_data_invocator.academy.data_parser.meta;

public enum AcademyDataColumnIndex {
    ACADEMY_REGION,
    ACADEMY_NAME,
    ACADEMY_TYPE,
    COURSE_TYPE,
    ACADEMY_ADDRESS,
    ACADEMY_REPRESENTATIVE,
    ACADEMY_CONTACT,
    COURSE_LINE,
    COURSE_CURRICULUM,
    COURSE_SUBJECT,
    COURSE_CAPACITY,
    COURSE_DURATION,
    COURSE_TIME,
    COURSE_BASIC_FEE,
    COURSE_TEST_FEE,
    COURSE_MATERIAL_FEE,
    ACADEMY_FOOD_FEE,
    ACADEMY_ACCOMMODATION_FEE,
    ACADEMY_SHUTTLE_FEE,
    ACADEMY_CLOTHES_FEE,
    COURSE_TOTAL_FEE,
    ACADEMY_TEACHER_COUNT;
}
